### ISSUE TITLE
KSV ubuntu 12.04 not started

### ISSUE THREAD

**Issue by audiserg** [kaitai-io/kaitai_struct_visualizer#8]
/var/lib/gems/1.8/gems/kaitai-struct-visualizer-0.5/bin/ksv:6: undefined method `realpath' for File:Class (NoMethodError)
	from /usr/local/bin/ksv:19:in `load'
	from /usr/local/bin/ksv:19

I dont understand ruby.

**Comment by GreyCat** [comment]
Guessing from /var/lib/gems/1.8 - it's Ruby 1.8 and the error is probably due to `File` missing `realpath` method in Ruby 1.8.

Technically, you can probably get it running by removing all lines 3-10, but there's no guarantee that anything will work later on, because Ruby 1.8 is [past end of life since 2013](http://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/) and is generally not supported anywhere.

The easiest way is probably to upgrade Ruby (and probably Ubuntu 12.04 - I'm not even sure if it has JVM 8+ to run the compiler), or just use [Web IDE](https://kt.pe/kaitai_struct_webide/)?

If you really want somehow to work with us on support for Ruby 1.8 — please tell us a bit about your situation, why should it be supported, why you can't switch to modern systems, etc.?

**Comment by audiserg** [comment]
i setup 1.9 ruby, and need next steps:
sudo gem uninstall kaitai-struct-visualizer
sudo rm -r /var/lib/gems
sudo gem install kaitai-struct-visualizer
KSV run

**Comment by GreyCat** [comment]
Sorry, I don't quite understand you. Everything's ok?

**Comment by audiserg** [comment]
KSV start but not ok, look to the new issue
